### ISSUE TITLE
qtile run JetBrains product (like idea) , only shows a white screen

### ISSUE THREAD

**Issue by ashcoll** [qtile/qtile#1189]
## qtile version 0.11.1
$ pip3.5 install --user qtile

## .xinitrc file
~/.local/bin/qtile --version

## run X
$ startx

## idea version :  ideaIU-2018.1.5
$ ./bin/idea.sh

  
------------------------------------------------------------------------------------------
## here is qtile config.py, just a copy of qtile.org config.py.
from libqtile import bar, hook, layout, widget
from libqtile.command import lazy
from libqtile.config import Click, Drag, Group, Key, Screen

wmname = 'qtile'
mod = 'mod4'

### Key bindings
keys = [
    # Window manager controls
    Key([mod, 'control'], 'r', lazy.restart()),
    Key([mod, 'control'], 'q', lazy.shutdown()),
    Key([mod], 'r', lazy.spawncmd()),
    Key([mod], 'Return', lazy.spawn('xterm')),
    Key([mod], 'w',      lazy.window.kill()),

    Key([mod], 'Tab', lazy.layout.next()),
    Key([mod], 'Left', lazy.screen.prevgroup()),
    Key([mod], 'Right', lazy.screen.nextgroup()),

    # Layout modification
    Key([mod, 'control'], 'space', lazy.window.toggle_floating()),

    # Switch between windows in current stack pane
    Key([mod], 'k', lazy.layout.down()),
    Key([mod], 'j', lazy.layout.up()),

    # Move windows up or down in current stack
    Key([mod, 'control'], 'k', lazy.layout.shuffle_down()),
    Key([mod, 'control'], 'j', lazy.layout.shuffle_up()),

    # Switch window focus to other pane(s) of stack
    Key([mod], 'space', lazy.layout.next()),

    # Toggle between different layouts as defined below
    Key([mod], 'Tab',    lazy.nextlayout()),
]

### Mouse bindings and options
mouse = (
    Drag([mod], 'Button1', lazy.window.set_position_floating(),
        start=lazy.window.get_position()),
    Drag([mod], 'Button3', lazy.window.set_size_floating(),
        start=lazy.window.get_size()),
)

bring_front_click = True
cursor_warp = False
follow_mouse_focus = True

### Groups
groups = [
    Group('a'),
    Group('s'),
    Group('d'),
    Group('f'),
    Group('u'),
    Group('i'),
    Group('o'),
    Group('p'),
]
for i in groups:
    # mod + letter of group = switch to group
    keys.append(Key([mod], i.name, lazy.group[i.name].toscreen()))

    # mod + shift + letter of group = switch to & move focused window to group
    keys.append(Key([mod, 'shift'], i.name, lazy.window.togroup(i.name)))

dgroups_key_binder = None
dgroups_app_rules = []

### Layouts
layouts = [
    layout.Max(),
    layout.Stack(num_stacks=2),
    layout.Tile(),
    layout.RatioTile(),
    layout.Matrix(),
]

floating_layout = layout.Floating()

### Screens and widget options
screens = [
    Screen(
        bottom=bar.Bar(
            widgets=[
                widget.GroupBox(
                    highlight_method='block',
                    inactive='999999'
                ),
                widget.Prompt(),
                widget.WindowName(),
                widget.Systray(),
                widget.Clock(format='%a %d %b %I:%M %p'),
            ],
            size=30,
            background=['222222', '111111'],
        ),
    ),
]

widget_defaults = dict(
    font='Arial',
    fontsize=15,
)

auto_fullscreen = True

def main(qtile):
    ''' This function is called when Qtile starts. '''
    pass

------------------------------------------------------------------
-------------------------------------------- 
start intellij idea, the launch window and the tips window is run correctly. 
but when launch finished, only show a whole big white screen , does nothing.

Thinks

**Comment by Sweenu** [comment]
Put `wmname = "LG3D"`. That should solve the it. It's a recurring problem with java programs.

**Comment by ashcoll** [comment]
## Yeah,  wmname = "LG3D" soveld my problem. export _JAVA_AWT_WM_NONREPARENTIN=1 can't. 
> Put wmname = "LG3D". That should solve it. It's a recurring problem with java programs.

## But I am confused. 
#558 

> I know from my xmonad days that lying about the wmname can also cause some bugs, in gtk for example (https://code.google.com/p/xmonad/issues/detail?id=559).

> The "correct" solution would be to get Java to fix the bug (http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8058197, http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8062657 and countless older reports) but it's been around for a long time and no one seems interested. 

### Question 1
I checked the java bug issue, it state is Fixed in jdk8u40, but i used is the latest java 1.8.0_172 and i test in java-10.0.2, it still show white screen. what's going on?
### Question 2
set wmname = "LG3D" can solved the java problem, set wmname else  can cause the problem, why and what does "LG3D" mean?

**Comment by ramnes** [comment]
We are not going to debug Java here, sorry. :smile:

**Comment by pawamoy** [comment]
> _JAVA_AWT_WM_NONREPARENTIN=1 can't.

It's because the last G is missing: `_JAVA_AWT_WM_NONREPARENTING=1` Exporting it worked for me, with `wmname = "qtile"` in my config.

**Comment by arielnmz** [comment]
Quick question, why does this not happen in other TWM? e.g. AwesomeWM doens't have this problem

**Comment by pawamoy** [comment]
Oh I think every window manager has its issues with Java. Just search "java" in i3, awesome, etc. and you'll see a lot of similar problems :smile:

**Comment by arielnmz** [comment]
True, Aswesome has its own share of issues itself, but I had never struggled specifically with Java on it, or at least when I started using it a couple years ago: I'm curious because setting the wmname or exporting that variable seem to be things that are not qtile-specific, neither of which I had to do on awesome, for example. Actually, I don't even know what wmname awesome sets for itself...

**Comment by pawamoy** [comment]
I guess these WM found settings that worked for them. I believe maintainers of Qtile sometimes got inspiration from their code :slightly_smiling_face: 

I think it would be very interesting to discuss with the maintainers of these other WM about the Java issues, and how they resolved them (or not).
