### ISSUE TITLE
Fullscreen-off windows are moved to the tail of the list of windows

### ISSUE THREAD

**Issue by whatacold** [qtile/qtile#1482]
It's a bit frustrating that toggling fullscreen of windows will mess up the window layout.
For example, it can be reproduced with a tile layout(configured by `layout.Tile(add_after_last=True)`):
1. Open 3 windows, and they looks like:

        |   | B
        | A |--
        |   | C

2. Toggle A into fullscreen, and toggle it off, then you will find A is moved to the tail of the window list, which makes them look like:

        |   | C
        | B |--
        |   | A

The reason for that, is that the window is removed from the list when it is toggled to fullscreen, as in [_Group.remove()](https://github.com/qtile/qtile/blob/master/libqtile/group.py#L274),

    def remove(self, win, force=False):
        ...
        if win.floating:
            ...
        else:
            for i in self.layouts:
                if i is self.layout:
                    nextfocus = i.remove(win)
                else:
                    i.remove(win)

I think maybe the window is better marked hidden, but is still kept in the list. But I haven't figured out how to fix it properly:(

**Comment by ramnes** [comment]
Can confirm. Super annoying.

**Comment by ramnes** [comment]
Related to #1114 #1201 #1202 and #1313. I think we can confirm that it happens on pretty much all layouts at this point. Let's find a global way to address this.

**Comment by gmjain** [comment]
Aren't we technically cheating by converting the window to floating when trying to make it fullscreen? There are some side-effects to that too. Like, a fullscreen floating window can now be dragged/resized using the click/drag bindings which is not (or shouldn't be) a property of a strictly fullscreen window.

I agree with @whatacold that we shouldn't remove it from the layout client list. I think a potential solution can be to not make it floating but just change its dimensions for rendering, overlapping the other windows in the layout.

**Comment by jwijenbergh** [comment]
Hey I'm still having this issue myself. Is the plan to move forward with #1313 or #1500? I am willing to help with these prs but I have never contributed to qtile myself.

**Comment by ramnes** [comment]
I don't know, I don't feel very enthusiastic about the two RPs; maybe just because they've been abandoned for a while, or maybe because I'm hopeful that we can do something simpler. So feel free to choose one, or to work on your own take.

**Comment by flexagoon** [comment]
Can confirm, the issue is very annoying

**Comment by VoltaireNoir** [comment]
Sadly this issue remains unresolved. This greatly hinders my workflow, and it is the only reason why I'm not using Qtile anymore. I really hope it gets fixed soon. I wish I could help but I'm not a coder. Perhaps a solution can be found by looking at other WMs like Spectrwm, Leftwm which don't have the same problem?

**Comment by elParaguayo** [comment]
The approach in #1313 is the way I'd probably go about this. Layouts are one of the bits I'm less familiar with but I'd be happy to pick this up.

**Comment by jwijenbergh** [comment]
I have some time to work on this now. I think #1313 does have its downsides, see https://github.com/qtile/qtile/pull/1500#issuecomment-566131219

#1500 on the other hand, seems like too many changes. Hopefully there's a solution that is simple and has the expected result.

**Comment by elParaguayo** [comment]
Interesting. 

Glad to hear you've got time. I'll leave you to it!

**Comment by jwijenbergh** [comment]
Just as a quick update:

I am currently continuing #1500, while these are a lot of changes I see no other way to do this properly. #1313 has the advantage that it's less code but it will be unable to fix more complex cases of floating and unfloating windows. E.g. if you float (including fullscreening) a window and then tile it again it it should get back to the initial position. However, when you do this for multiple windows and then tile them again it's hard to restore them to the intial position as the indices of the original list have been changed. It's also difficult to implementing restoring for more complex layouts that have manual intervention (index based restoring won't work here possibly).

#1500 takes a different approach by not removing the clients from the layout list but instead skip over them if they're floating. At a glance, AwesomeWM, SpectrWM, DWM all do it this way. It still needs some manual intervention for the TreeTab layout and possibly the Bsp layout. Because not much code has changed in the layouts since the original pr, I will make a draft in the next few days that fixes the issue for most layouts.

**Comment by neworld** [comment]
Even as an author of #1313 I would like #1500 solution more, because it looks cleaner conceptually, even code is not. But for me, good concepts are always more important than code.

**Comment by VoltaireNoir** [comment]
@jwijenbergh Any update on the progress? Sorry but I am just desperately waiting for this bug to get fixed 😅

**Comment by jwijenbergh** [comment]
> 
> 
> @jwijenbergh Any update on the progress? Sorry but I am just desperately waiting for this bug to get fixed 😅

Still working on it, sorry for the delay. I'm still busy with other things. I will see if I can get a pr going this weekend though

**Comment by VoltaireNoir** [comment]
> > @jwijenbergh Any update on the progress? Sorry but I am just desperately waiting for this bug to get fixed sweat_smile
> 
> Still working on it, sorry for the delay. I'm still busy with other things. I will see if I can get a pr going this weekend though

That's great! Oh and don't worry about it. Please take all the time you need.

**Comment by jwijenbergh** [comment]
See #2724, let me know if this code works as expected.

**Comment by eboody** [comment]
thanks for working on this guys!!

**Comment by VoltaireNoir** [comment]
Unfortunately #2724 PR doesn't seem to have worked out as intended. I wonder if this issue will get fixed anytime soon.

**Comment by jwijenbergh** [comment]
My apologies for not working on #2724 for a while. The problem with my approach is that I tried to create a solution that works like other window managers (they simply skip over windows that are non tiled in the layout). However, these other window managers mostly all have list based layouts which makes this problem rather trivial to implement. As Qtile has a vast variety of layouts and underlying data structures my solution is too complex. For example I would have to add extra code that hides columns in the Columns layout that only have floating windows in them and then unhides it again later. I propose an easier solution that instead of toggling the window floating and then fullscreening it works like follows:
- A fullscreen 'layout' is added that behaves like the max layout but covers the bar
- When a window is toggled fullscreen this layout is enabled and doing a mod+j and mod+k moves to the next window in the stack still in fullscreen
- Toggling off fullscreen simply reverts back to the old layout

The only problem I can see with this approach is that it does not fix the re-ordering where a tiled window is set to floating and then tiled again, however this issue is only for the fullscreen behaviour and I think that it does make sense to fully remove a window from the layout when it is set to floating.

**Comment by VoltaireNoir** [comment]
> 

I think this solution makes a lot of sense. And I only see re-ordering as an issue when it comes to toggling full-screen on and off. As you said, it makes sense to remove a window from a layout when it is set to floating; it doesn't have to retain it's earlier position in the tiled layout.

**Comment by VoltaireNoir** [comment]
> My apologies for not working on #2724 for a while. The problem with my approach is that I tried to create a solution that works like other window managers (they simply skip over windows that are non tiled in the layout). However, these other window managers mostly all have list based layouts which makes this problem rather trivial to implement. As Qtile has a vast variety of layouts and underlying data structures my solution is too complex. For example I would have to add extra code that hides columns in the Columns layout that only have floating windows in them and then unhides it again later. I propose an easier solution that instead of toggling the window floating and then fullscreening it works like follows:
> 
>     * A fullscreen 'layout' is added that behaves like the max layout but covers the bar
> 
>     * When a window is toggled fullscreen this window is added to the fullscreen layout and this layout is set as active
> 
>     * Toggling off fullscreen simply reverts back to the old layout
> 
> 
> The only problem I can see with this approach is that it does not fix the re-ordering where a tiled window is set to floating and then tiled again, however this issue is only for the fullscreen behaviour and I think that it does make sense to fully remove a window from the layout when it is set to floating.

I think this solution makes a lot of sense. And I only see re-ordering as an issue when it comes to toggling full-screen on and off. As you said, it makes sense to remove a window from a layout when it is set to floating; it doesn't have to retain it's earlier position in the tiled layout.

**Comment by VoltaireNoir** [comment]
I haven't been using Qtile from a while and I installed the latest version yesterday and start playing around with it again, only to notice that the issue is no longer there. The windows that are switched to fullscreen and back to normal no longer change their position. Could it be that it was fixed in the last update? Can anyone else confirm this? @jwijenbergh ?

**Comment by jwijenbergh** [comment]
> I haven't been using Qtile from a while and I installed the latest version yesterday and start playing around with it again, only to notice that the issue is no longer there. The windows that are switched to fullscreen and back to normal no longer change their position. Could it be that it was fixed in the last update? Can anyone else confirm this? @jwijenbergh ?

It could be that there is some difference between qtile versions but it's definitely not fixed for me. Which layout are you using? is it xmonad possibly? Try to add 2 windows in the xmonad layout and fullscreen the first window on and off. Another easy way to verify that it is broken is to use the treetab layout.

**Comment by jwijenbergh** [comment]
I have made a variation of my proposal in #3057, please test and report issues in that pr.

**Comment by VoltaireNoir** [comment]
> > I haven't been using Qtile from a while and I installed the latest version yesterday and start playing around with it again, only to notice that the issue is no longer there. The windows that are switched to fullscreen and back to normal no longer change their position. Could it be that it was fixed in the last update? Can anyone else confirm this? @jwijenbergh ?
> 
> It could be that there is some difference between qtile versions but it's definitely not fixed for me. Which layout are you using? is it xmonad possibly? Try to add 2 windows in the xmonad layout and fullscreen the first window on and off. Another easy way to verify that it is broken is to use the treetab layout.

Sorry, my bad. I think I didn't properly clean up the previous installation (I was testing your previous pr) and that somehow affected the version of qtile I installed through the Arch repo this time. I did a clean install again and yes the issue is still there. Going to test your new pr now. Thanks! Will report any issues there.

**Comment by jwijenbergh** [comment]
> > > I haven't been using Qtile from a while and I installed the latest version yesterday and start playing around with it again, only to notice that the issue is no longer there. The windows that are switched to fullscreen and back to normal no longer change their position. Could it be that it was fixed in the last update? Can anyone else confirm this? @jwijenbergh ?
> > 
> > 
> > It could be that there is some difference between qtile versions but it's definitely not fixed for me. Which layout are you using? is it xmonad possibly? Try to add 2 windows in the xmonad layout and fullscreen the first window on and off. Another easy way to verify that it is broken is to use the treetab layout.
> 
> Sorry, my bad. I think I didn't properly clean up the previous installation (I was testing your previous pr) and that somehow affected the version of qtile I installed through the Arch repo this time. I did a clean install again and yes the issue is still there. Going to test your new pr now. Thanks! Will report any issues there.

Okay good. Thank you! Make sure to re-pull as I just force pushed some crucial changes

**Comment by milkias17** [comment]
For anyone who wants a temporary solution until this issue is fixed by the devs you can use this function.
`def toggle_fullscreen_hack(qtile):
    screen = qtile.current_screen
    layout = qtile.current_layout
    for c_bar in [screen.left, screen.right, screen.top, screen.bottom]:
        if c_bar and layout.cmd_info()["name"] == "max":
            qtile.cmd_to_layout_index(0)
            if not c_bar.is_show():
                c_bar.show(is_show=True)
        elif c_bar and layout.cmd_info()["name"] != "max":
            qtile.cmd_to_layout_index(1)
            if c_bar.is_show():
                c_bar.show(is_show=False)
`
And then instead of using lazy.toggle_fullscreen in your keybindings use lazy.function(toggle_fullscreen_hack).
NB: this assumes that the max layout is index 1 in layouts variable.

**Comment by jwijenbergh** [comment]
Can someone let me know if #3057 fixes it?

**Comment by stefur** [comment]
I tested #3057 now. Works like a charm on my end. Thanks @jwijenbergh!

**Comment by jwijenbergh** [comment]
> I tested #3057 now. Works like a charm on my end. Thanks @jwijenbergh!

Great!

> Any hope to get #3057 merged soon? I'm waiting for it to move to qtile.

It still needs tests, let me add them now, rebase and them mark it ready for review

**Comment by jwijenbergh** [comment]
#3057 is merged, this can be closed 🎉
