### ISSUE TITLE
Turning any window static causes widgets to not render.

### ISSUE THREAD

**Issue by Craksy** [qtile/qtile#1810]
# Issue description
Making any window `static` either from an InteractiveCommandInterface or through a window object passed by the client_new hook causes several widgets, namely (A)Groupbox, Tasklist, and Prompt to not render(probably others too). CPUGraph, Clock and Volume seem to be rendering just fine.
Perhaps it's also worth noting that i can still click these widgets, and they react as they are supposed to. they just don't visually update. I've tried on Konsole, D-Feet popups, and a small app of my own.

# Qtile version
Qtile 0.15.1.dev160+gc427c9ef.d20200712 (fresh download)

# Stack traces
There are not really any errors or stack traces. The only thing i could find out of the ordinary in the logs is a couple of entries with an "Unhandled event: Expose" which were recorded whenever another window was opened in front of the static window, and then removed.
I attached the log output from a single session showcasing the error below.
[qtile-issue.log](https://github.com/qtile/qtile/files/4909474/qtile-issue.log)

and here's the xprop output for the static window that caused it (actually not from the same session, but produced in exactly the same fassion except in my main setup)
`_NET_WM_USER_TIME(CARDINAL) = 7766934
_NET_WM_DESKTOP(CARDINAL) = 4
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
WM_WINDOW_ROLE(STRING) = "MainWindow#1"
_NET_WM_ICON_NAME(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = "~ : ipython"
_NET_WM_NAME(UTF8_STRING) = "~ : ipython — Konsole"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x3e, 0x7e, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x1400009
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
                window id # of group leader: 0x1400009
WM_CLIENT_MACHINE(STRING) = "amnesia"
_NET_WM_PID(CARDINAL) = 73162
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 20971528
WM_CLASS(STRING) = "konsole", "konsole"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified size: 951 by 1042
                program specified minimum size: 4 by 4
                window gravity: Static
`

# Configuration
Trying to narrow down the the problem i ultimately ended with a fresh copy of rep, clean of any careless hacking of mine, using the default configuration, and still had the error. I've had the error in both the testing environment and my main configuration.
The session i attached log ouput from however was initiated with 
`LOG_LEVEL=DEBUG ./scripts/xephyr -c ./libqtile/resources/default_config.py`

I'm sorry i can't be more helpful in terms of providing useful details. If there's any additional information you need, please let me know.

**Comment by tych0** [comment]
All those (broken) widgets iterate over the list of the group's windows, maybe something about making a window static or similar that causes problems? Seems like the code is looking for something that's not there, and then dying halfway through drawing an update.

Weird that you don't get an exception though. I looked through our bare "except:" clauses and none of them look suspicious. Maybe try a bare "except:" in the individual widget update methods and see if you can get an error there?

**Comment by Craksy** [comment]
I wasn't able to get any exceptions. 
while attempting to do so i discovered that the `draw()` methods of the widgets are never called after making a window static.
the `Static` instance will cause qtile to `update_gaps` upon creation, which in turn will resize the screen and re-`_configure()` the bar.
When the `_configure()` method of the bar is called a second time, each widget reference is replaced with a `widget.base.Mirror` which for some reason fails to call it's "reflections" draw method.
until i figure out what is going on, explicitly calling the reflections `draw` method seems to do the trick, without producing any weird side effect.
```python
    #in bar.py
    def _actual_draw(self):
        self.queued_draws = 0
        self._resize(self.length, self.widgets)
        for i in self.widgets:
            i.reflects.draw() if hasattr(i, 'hook') else i.draw()
```

it's still weird that i'm not getting any actual errors though. And that noone else has experienced anything similar.

**Comment by tych0** [comment]
Thanks for debugging! Seems like it's a bug that we replace widgets with their Mirror if they're not actually Mirrored (and an additional bug that they don't call the underlying draw()). @m-col thoughts?

**Comment by m-col** [comment]
Interesting! This looks to be related to #1654 and it also looks like you've tracked it one step further. With the mirror widgets, you can use the same widget on 2 bars:
```python
cpugraph = CPUGraph()
bar1 = Bar(cpugraph)
bar2 = Bar(cpugraph)
```
When `_configure` is run on the bars (and therefore widgets), if a widget has been configured previously it's reference is replaced with a `Mirror` and that bar uses that instead. What hasn't been accounted for is that `bar._configure` is also run when you described, and then it makes all widgets mirrors, as by this point they've all been configured (or mirrored already).

I think setting `widget.configured` to False for all widgets at the start of the reconfigure should fix it, or alternatively just not reconfiguring widgets at all. @Craksy could you see if it happens with this patch:
[patch.txt](https://github.com/qtile/qtile/files/4926419/patch.txt)

**Comment by m-col** [comment]
I tried to reproduce it and actually I don't think that patch will fix it. I can take a closer look at what's going on - I'm also trying to set up a static window and getting these problems.

**Comment by m-col** [comment]
@Craksy please could you try [this branch](https://github.com/m-col/qtile/tree/simple_reconfigure_bar)?

**Comment by Craksy** [comment]
> @Craksy please could you try [this branch](https://github.com/m-col/qtile/tree/simple_reconfigure_bar)?

I just tried it and unfortionately it didn't solve the issue.
It did however, when i tried to open Konsole, grab my entire keyboard, only alowing recognized keysyms (sort of like a permanent KeyChord mode) which was sort of interesting.
this persisted until i closed the associated window and then everything was back to normal. xterm was working just fine
the bar however showed more or less same behavior as before. i didn't investigate further yet, but my guess would be that it's the same error.

**Comment by m-col** [comment]
Oh, that sucks I thought it would help. When you opened konsole that was just
running normally without any static windows? What are you doing to make a static
window? Then i can try to recreate it

**Comment by Craksy** [comment]
Mostly i've just lanched a session using the default config, hit M-r to spawn konsole start an IPython repl and just make that same window static like so
```python
In [1]: from libqtile.command_client import InteractiveCommandClient                          

In [2]: c = InteractiveCommandClient()                                                        

In [3]: win = c.window                                                                        

In [4]: win.static(0, 100, 100, 500, 500)
```
i've also done it from my config using the provided hooks, but it didn't seem to make a difference so the repl approach was a bit more convenient for debugging

i followed your advice btw, and just disabled the mirror part entirely in my main setup. i'm only running a single screen anyway, so it's an excellent temporary solution

**Comment by m-col** [comment]
On that simple_reconfigure_bar branch, when I run those 4 python lines in a repl everything appears to work fine: the window becomes static, all windows and keybindings work as normal and my 2 bars and all their widgets (many of which are mirror widgets) work as expected. This is on default config. I'm a bit confused as to what is different between what we have run. How does your GroupBox widget behave before/during/after having the static window open? What about if you try it with just xterm rather than konsole?

**Comment by Craksy** [comment]
I feel like a bit of an idiot... I tried again today and somehow magically it just worked.
I have this feeling that i just miiight have forgotten to actually switch the branch. I was very tired, okay.

Anyway, i can confirm that this fixes the issue.

**Comment by m-col** [comment]
Phew! That is good news. I just need to confirm that the commit works as intended when a window has strut hints, and then I can submit the PR.

**Comment by m-col** [comment]
Should be fixed by #1820. Can you confirm @Craksy?

**Comment by Craksy** [comment]
> Should be fixed by #1820. Can you confirm @Craksy?

Positive.
Just did the merge, and everything seems to be in order! ^^
