### ISSUE TITLE
Switching Groups on Program Start

### ISSUE THREAD

**Issue by Sawrz** [qtile/qtile#1958]
Hi,
I use Qtiles Matches to sort my programs into specific groups automatically. That works well. However, I want to take this whole thing a step further:

Let's suppose my active group is called "Code". Now, I want to start Firefox, which starts in a group "Web" because of my rules. Instead of pressing my keybinding for Firefox and manually switching to "Web", I automatically want to do the group switch. 
In other words: If a program starts in group A, change to group A.

I found a hook, which looks promising but it seems not to work:
``` Python
@hook.subscribe.client_new
def func(c):
    with open('tmp.txt', 'a') as file:
        from time import time
        log = f'{time()}: {c.name}, {c.group.name} \n'
        file.write(log)
```

Obviously this code doesn't change the group yet, but the hook doesn't fire each time I start a new program. So far, I understood Qtile should fill ```tmp.txt``` with the client's name and group each time I start a new program, e.g., Firefox. But that doesn't happen.

If the hook worked, my code would like something like this:
``` Python
@hook.subscribe.client_new
def auto_change_group(client):
    client.screen.togglegroup(groupName=client.group.name)
```

Any ideas what the problem is?

**Comment by tych0** [comment]
I've implemented this slightly differently, perhaps this will work for you instead: https://github.com/qtile/qtile-examples/blob/master/tych0/config.py#L119

**Comment by Sawrz** [comment]
It doesn't seem to work in my configuration. I copied the following from your configuration file:
``` Python
def app_or_group(group, app):
    """ Go to specified group if it exists. Otherwise, run the specified app.
    When used in conjunction with dgroups to auto-assign apps to specific
    groups, this can be used as a way to go to an app if it is already
    running. """
    def f(qtile):
        try:
            qtile.groupMap[group].cmd_toscreen()
        except KeyError:
            qtile.cmd_spawn(app)
    return f
```
I added the following to my `keys`:

``` Python
Key(DAILY_USAGE, "y", lazy.function(app_or_group('Development', 'google-chrome'))),
```

I made sure the group "Development" exists. See here:
``` Python
Group(name='Development',
          matches=[matches['Development']],
          exclusive=True,
          position=2,
          layout='monadtall',
          label=fa.icons['code']),
```

My full configuration file (without the changes I posted) is [here](https://gitlab.com/lazymedia/dotfiles/-/blob/master/.config/qtile/config.py).

It doesn't matter if Google Chrome already runs or not. Using my keybinding, nothing happens. You specified qtile ad a function parameter. I assume this is a global variable defined somewhere in the backend?

**Comment by tych0** [comment]
You probably need to port it to camel case of you're using a recent version of qtile, i.e. group_map

On Wed, Nov 11, 2020, at 6:50 AM, Sandro Wrzalek wrote:
> 

> It doesn't seem to work in my configuration. I copied the following from your configuration file:

> def app_or_group(group, app):
    """ Go to specified group if it exists. Otherwise, run the specified app.
>     When used in conjunction with dgroups to auto-assign apps to specific
>     groups, this can be used as a way to go to an app if it is already
>     running. """
    def f(qtile):
        try:
            qtile.groupMap[group].cmd_toscreen()
        except KeyError:
            qtile.cmd_spawn(app)
    return f
> I added the following to my `keys`:

> Key(DAILY_USAGE, "y", lazy.function(app_or_group('Development', 'google-chrome'))),
> I made sure the group "Development" exists. See here:

> Group(name='Development',
          matches=[matches['Development']],
          exclusive=True,
          position=2,
          layout='monadtall',
          label=fa.icons['code']),

**Comment by Sawrz** [comment]
I changed from CamelCase but the result is still the same: still nothing. I use 0.16.1, so it should be the most recent version.

``` Python
def app_or_group(group, app):
    """ Go to specified group if it exists. Otherwise, run the specified app.
    When used in conjunction with dgroups to auto-assign apps to specific
    groups, this can be used as a way to go to an app if it is already
    running. """
    def f(qtile):
        try:
            qtile.group_map[group].cmd_toscreen()
        except KeyError:
            qtile.cmd_spawn(app)
    return f
```

**Comment by tych0** [comment]
Check your logs, I'm guessing there's some kind of stack trace there?

**Comment by Sawrz** [comment]
After posting my last reply, I had the same idea to check the logs. But I can't find any Qtile log in `/var/logs/`. I thought about forcing the output to a log file with `qtile > my.log`, but I'm not sure if this doesn't create multiple Qtile instances on top of each other, leading to other weird behaviors.
Do I need to pass additional settings to Qtile, or did you use a different location than `/var/logs` for the log files?

**Comment by tych0** [comment]
The github issue template has the log locations in it :-)

**Comment by Sawrz** [comment]
Sorry for taking so long. It seems that `group_map` does not exist:

``` 
2020-11-19 11:55:52,411 WARNING libqtile manager.py:maybe_restart():L269 Restarting Qtile with os.execv(...)
2020-11-19 11:55:52,744 WARNING libqtile xcursors.py:_setup_xcursor_binding():L112 xcb-cursor not found, fallback to font pointer
2020-11-19 11:55:59,877 ERROR libqtile command_object.py:cmd_function():L206 Exception calling "<function app_or_group.<locals>.f at 0x7fe96bbcd9d0>":
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/libqtile/command_object.py", line 203, in cmd_function
    function(self, *args, **kwargs)
  File "/home/sandro/.config/qtile/config.py", line 89, in f
    qtile.group_map[group].cmd_toscreen()
AttributeError: 'Qtile' object has no attribute 'group_map'
```

**Comment by ramnes** [comment]
It's `groups_maps`, not `group_map`.

https://github.com/qtile/qtile/blob/master/libqtile/core/manager.py#L82

**Comment by Sawrz** [comment]
That solved my issue, and another as well. Thank you so much! =)
