### ISSUE TITLE
Click-through drop-down menus on the web

### ISSUE THREAD

**Issue by ArtemSmaznov** [qtile/qtile#2404]
# Issue description
Items in hover/drop-down menus on the web do not register click and instead the page underneath the menu gets clicked.
This happens on a number of web sites but easiest I can think of is duolingo as there is a language menu that does not require an account. I am not sure if drop-down menus on all sites are behaving like this.

- I have reproduced it using the Brave / Chrome / Vivaldi browsers while on qtile.
- Reproduced it on both my PCs as well as with the default config on a new test user on the system.
- Reproduced it after disabling my picom compositor and rebooting.
- I was not able to reproduce the issue on AwesomeWM nor Cinnamon which makes me believe that this is caused by qtile

# Repro Steps
1. Open a GUI web browser
2. Navigate to https://www.duolingo.com/
3. Click "Site language: English" link on the top right
4. Select any other language

# Expected behavior
Click should be registered on the drop-down menu and the new language should be selected

# Actual result
The language selection menu closes and the new language is not selected. Instead the click registered on the page behind the menu (if there was another link under the menu where the cursor was it would have been clicked)

The only way to navigate these menus is to middle click (or right click and select open in new tab) them to open in new tab and close the old one which is quite annoying.

# Reproduction rate
20/20

# Qtile version
0.17.0-1

# Stack traces
n/a (blank logs)

# Configuration
Reproducible on default config

# System info
Arch Linux x86_64
Kernel: Linux 5.11.15-arch1-2

**Comment by elParaguayo** [comment]
Yes - I have this bug too. See #1809 for an example.

**Comment by ArtemSmaznov** [comment]
Thanks, that does seem exactly the same as described in the comments there. The title threw me off

**Comment by ramnes** [comment]
Yeah, this bug is incredibly boring, especially since it doesn't happen on all drop-down menus.

Workarounds so far are either to middle-click (and thus open in a new tab), or right-click then left-click on the link (yes, that's weird, but it works). Or navigating the menu with the keyboard when it works.

Related issues (or possibly related): #1792 #1809 #1824

**Comment by elParaguayo** [comment]
Any ideas how we'd approach debugging this? Is this something to do with how we handle mouse clicks in windows?

I'd love to help but not sure I have the skills.

**Comment by ramnes** [comment]
I usually start by looking at the logs. This is what happens when I click on the Duolingo menu:

```
2021-04-21 10:31:12,227 libqtile core.py:_xpoll():L276  EnterNotify
2021-04-21 10:31:12,228 libqtile core.py:_get_target_chain():L355  Unhandled event: EnterNotify
2021-04-21 10:31:12,228 libqtile core.py:_xpoll():L276  ButtonPress
2021-04-21 10:31:12,229 libqtile core.py:_xpoll():L279  Handling: ButtonPress
2021-04-21 10:31:12,229 libqtile manager.py:process_button_click():L774  Ignoring unknown button: 1
2021-04-21 10:31:12,229 libqtile manager.py:process_button_click():L774  Ignoring unknown button: 1
2021-04-21 10:31:12,229 libqtile interface.py:call():L311  Command: function((<function Qtile.load_config.<locals>.noop at 0x7f23da278af0>,), {})
2021-04-21 10:31:12,231 libqtile hook.py:fire():L370  Internal event: client_focus((Window("Duolingo - La meilleure façon d'apprendre une langue - Google Chrome"),), {})
2021-04-21 10:31:12,241 libqtile hook.py:fire():L370  Internal event: client_focus((Window("Duolingo - La meilleure façon d'apprendre une langue - Google Chrome"),), {})
2021-04-21 10:31:12,246 libqtile hook.py:fire():L370  Internal event: client_focus((Window("Duolingo - La meilleure façon d'apprendre une langue - Google Chrome"),), {})
2021-04-21 10:31:12,247 libqtile hook.py:fire():L370  Internal event: client_focus((Window("Duolingo - La meilleure façon d'apprendre une langue - Google Chrome"),), {})
2021-04-21 10:31:12,249 libqtile hook.py:fire():L370  Internal event: client_focus((Window("Duolingo - La meilleure façon d'apprendre une langue - Google Chrome"),), {})
2021-04-21 10:31:12,250 libqtile hook.py:fire():L370  Internal event: client_focus((Window("Duolingo - La meilleure façon d'apprendre une langue - Google Chrome"),), {})
2021-04-21 10:31:12,251 libqtile hook.py:fire():L370  Internal event: client_focus((Window("Duolingo - La meilleure façon d'apprendre une langue - Google Chrome"),), {})
2021-04-21 10:31:12,252 libqtile hook.py:fire():L370  Internal event: focus_change((), {})
2021-04-21 10:31:12,257 libqtile hook.py:fire():L370  Internal event: client_focus((Window("Duolingo - La meilleure façon d'apprendre une langue - Google Chrome"),), {})
2021-04-21 10:31:12,258 libqtile hook.py:fire():L370  Internal event: client_focus((Window("Duolingo - La meilleure façon d'apprendre une langue - Google Chrome"),), {})
2021-04-21 10:31:12,259 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,259 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,260 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,260 libqtile core.py:_xpoll():L276  ConfigureNotify
2021-04-21 10:31:12,261 libqtile core.py:_get_target_chain():L355  Unhandled event: ConfigureNotify
2021-04-21 10:31:12,261 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,261 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,261 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,262 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,262 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,262 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: ZOOM
2021-04-21 10:31:12,263 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,263 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,264 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,264 libqtile core.py:_xpoll():L276  ConfigureNotify
2021-04-21 10:31:12,264 libqtile core.py:_get_target_chain():L355  Unhandled event: ConfigureNotify
2021-04-21 10:31:12,265 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,265 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,265 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,266 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,266 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,266 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: ZOOM
2021-04-21 10:31:12,267 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,268 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,269 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,270 libqtile core.py:_xpoll():L276  ConfigureNotify
2021-04-21 10:31:12,270 libqtile core.py:_get_target_chain():L355  Unhandled event: ConfigureNotify
2021-04-21 10:31:12,271 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,272 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,272 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,272 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,273 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,273 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,273 libqtile core.py:_xpoll():L276  ConfigureNotify
2021-04-21 10:31:12,273 libqtile core.py:_get_target_chain():L355  Unhandled event: ConfigureNotify
2021-04-21 10:31:12,274 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,274 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,274 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,274 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,274 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,274 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,275 libqtile core.py:_xpoll():L276  ConfigureNotify
2021-04-21 10:31:12,275 libqtile core.py:_get_target_chain():L355  Unhandled event: ConfigureNotify
2021-04-21 10:31:12,275 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,275 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,275 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,276 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,276 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,276 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,276 libqtile core.py:_xpoll():L276  ConfigureNotify
2021-04-21 10:31:12,276 libqtile core.py:_get_target_chain():L355  Unhandled event: ConfigureNotify
2021-04-21 10:31:12,277 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,277 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,277 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,277 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,277 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,278 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,278 libqtile core.py:_xpoll():L276  ConfigureNotify
2021-04-21 10:31:12,278 libqtile core.py:_get_target_chain():L355  Unhandled event: ConfigureNotify
2021-04-21 10:31:12,278 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,278 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,279 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,279 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,279 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,279 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,279 libqtile core.py:_xpoll():L276  ConfigureNotify
2021-04-21 10:31:12,280 libqtile core.py:_get_target_chain():L355  Unhandled event: ConfigureNotify
2021-04-21 10:31:12,280 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,280 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,280 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: WM_STATE
2021-04-21 10:31:12,280 libqtile core.py:_xpoll():L276  LeaveNotify
2021-04-21 10:31:12,281 libqtile core.py:_get_target_chain():L355  Unhandled event: LeaveNotify
2021-04-21 10:31:12,281 libqtile core.py:_xpoll():L276  EnterNotify
2021-04-21 10:31:12,281 libqtile core.py:_xpoll():L279  Handling: EnterNotify
2021-04-21 10:31:12,281 libqtile hook.py:fire():L370  Internal event: client_mouse_enter((Window("Duolingo - La meilleure façon d'apprendre une langue - Google Chrome"),), {})
2021-04-21 10:31:12,281 libqtile core.py:_xpoll():L276  PropertyNotify
2021-04-21 10:31:12,282 libqtile core.py:_xpoll():L279  Handling: PropertyNotify
2021-04-21 10:31:12,282 libqtile window.py:handle_PropertyNotify():L1244  PropertyNotifyEvent: _NET_WM_USER_TIME
2021-04-21 10:31:12,282 libqtile window.py:handle_PropertyNotify():L1280  Unknown window property: _NET_WM_USER_TIME
2021-04-21 10:31:12,295 libqtile core.py:_xpoll():L276  ConfigureNotify
2021-04-21 10:31:12,296 libqtile core.py:_get_target_chain():L355  Unhandled event: ConfigureNotify
```

Then I try to mess with the code. :)

**Comment by m-col** [comment]
`_NET_WM_USER_TIME`! I recognise that from the issue about clicking on PyCharm
having problems -- a lead?

**Comment by ramnes** [comment]
Commenting this line https://github.com/qtile/qtile/blob/3dcad2ca9de206603b67f2b9ae260abe5cf914d0/libqtile/core/manager.py#L139 fixes it, but then we don't have focus on click anymore. :)

**Comment by elParaguayo** [comment]
I'll do some more digging later on but, if you take that line out, it seems that `process_button_click` is not processed at all which would explain why you don't get focus on click.

However, I can't see any obvious reason by the method isn't run.

**Comment by ramnes** [comment]
Yeah, this line is here to add a fake binding on Button1 so that process_button_click is called, and thus _focus_by_click as well.

**Comment by ArtemSmaznov** [comment]
Any chance a check if the window is already focused can solve the problem so that, if it is, nother extra is executed?

**Comment by ramnes** [comment]
Nah, this can't work. I've been spending the whole day on this, and it seems that as long as the button is grabbed, which happens if we define a Click for Button1, the problem happens. I think Chrome needs to grab it as well for this kind of menus, and can't do it if we have it grabbed. I"m not sure why, and I'm really not sure what we can do about this.

We could start by only defining that Click for users with `follow_mouse_focus = False`. It doesn't make sense to focus a window on click if we're already focusing it anyway. This would fix the bug for people that didn't change the default value of this setting, i.e. most people, I guess.

@tych0 @m-col @flacjacket thoughts?

**Comment by ramnes** [comment]
Relevant stuff:
* https://tronche.com/gui/x/xlib/input/pointer-grabbing.html
* https://chromium.googlesource.com/chromium/src/+/master/ui/base/x/x11_pointer_grab.cc
* https://github.com/qtile/qtile/blob/3dcad2ca9de206603b67f2b9ae260abe5cf914d0/libqtile/backend/x11/core.py#L479-L508

**Comment by tych0** [comment]
I see at least the same behavior from https://github.com/qtile/qtile/issues/1792 and have:

```
# do not do anything with the mouse
mouse = []
```

In my config, does that mean i shouldn't see this?

**Comment by ramnes** [comment]
Nah, because that Click is always added: https://github.com/qtile/qtile/blob/3dcad2ca9de206603b67f2b9ae260abe5cf914d0/libqtile/core/manager.py#L139

Another solution would be to add a `focus_on_click` config variable. It can be combined with what I've suggested on my previous comment to restrict even more the scope of this bug.

**Comment by tych0** [comment]
Oh, yes. And as I recall that actually fixes a bug for some people. What if we figure out how to fix that bug for real, then do we get this for free?

I guess not, because people using mouse actions will still have this problem.

**Comment by ramnes** [comment]
Yes that would work. People would only have this bug if they define a `Click([], "Button1", ...)` (i.e. without mod), which is not likely to happen, and that we can forbid if we want to be sure.

**Comment by ramnes** [comment]
The issue you're referring to is #125. There was a first implementation that didn't grab the key but apparently had side effects (#269). The PR that got merged is #365.

**Comment by ramnes** [comment]
FWIW `xinput --test-xi2 --root` grabs all mouse events and still has these menus clickable on Chrome, so we're definitely doing something wrong here. :)

https://github.com/freedesktop/xorg-xinput/blob/master/src/test_xi2.c

**Comment by tych0** [comment]
When you do that, what does the xtrace say?

**Comment by Graeme22** [comment]
FWIW, as an everyday user I'd have to say this bug and #1824 are major annoyances, I wouldn't be surprised if some users have left due to these.

**Comment by ramnes** [comment]
Hence the "priority" label on each of these. :)

**Comment by HackMEAny** [comment]
For websites & even in the search bar on clicking any suggestion it doesn't work

- blockchain.com (try to click on the menu button "...") 
- many others website not taking names individually

**Comment by FluffMe** [comment]
The issue seems to go away if I launch chromium-based browsers with `--disable-features=SendMouseLeaveEvents`
https://bugs.chromium.org/p/chromium/issues/detail?id=713746 might be relevant?

**Comment by mitic-alexander** [comment]
So, I don't know if this will help, but let's give it a go.

I am using the Brave browser on Arch (brave-bin from the AUR). I am using the Columns layout primarily.

I am unable to click on my dropdown login info on any website I use, as well as being unable to click on links, such as the one mentioned in the initial bug report on Duolingo. Once I switch to the Max layout, I can click on my dropdown login info, but still can't click on dropdown menus, like the one on Duolingo. Clicking while holding "Ctrl" lets me click links, although it sometimes opens a new tab, depending on the website. (I know it's not a fix, but if someone's waiting for a fix, this might help a little while they wait.)

**This might be more useful.** I tried out the Brave (non-binary version), from the Chaotic AUR repo. It was 'Version 1.19.92 Chromium: 88.0.4324.152 (Official Build) unknown (64-bit)'. **_Everything worked fine with that Brave version. Same PC, same Qtile setup, same everything._**

Hope it gives someone some ideas, or at least a place to start looking. If I can help somehow, please leave a comment and I'll reply ASAP.

P.S. Sorry for the novel of a comment.

**Comment by m-col** [comment]
I used xterm as my main terminal for the past year or so and have had no issues with clicking, and I just tested a bunch of commits both before and after #2413 was merged and they were all good. The comment beside the no-op Button1 binding specified xterm as being troublesome... it seems likely that any issue there was fixed? In any case I'd be in favour of removing that no-op and fixing any bug the right way if/when it appears.

> People would only have this bug if they define a Click([], "Button1", ...) (i.e. without mod), which is not likely to happen

So this would solve the issue completely?

**Comment by ramnes** [comment]
#2413 didn't fix anything, it's just some code cleaning. About that xterm comment, IIRC it was very old and not even related to the no-op function, which has been removed, yes.

And yes, I'm pretty sure that fixing #125 without relying on a `Click` would solve this issue completely.

**Comment by m-col** [comment]
Does #2503 fix the issue?

**Comment by elParaguayo** [comment]
Works for me on Brave.

**Comment by m-col** [comment]
Alright, take 2, does https://github.com/qtile/qtile/pull/2506 fix it?

**Comment by ramnes** [comment]
@m-col Anything that removes the `Click` will fix this and the other similar bugs, the question is rather if we encounter any other bug while trying your branch. :)

**Comment by ramnes** [comment]
It should now be fixed in master as #2506 got merged. Please comment if that's not the case and I'll re-open. Thanks!
