### ISSUE TITLE
Wayland Qtile current git master crashes when the first window is opened

### ISSUE THREAD

**Issue by arjan-s** [qtile/qtile#3298]
I'm usually running the latest git master on Wayland to test the latest additions/fixes and to be able to merge in patches. I know this is not necessarily a good idea, so this issue is just to notify you of a new problem.
The current git master crashes silently when the first window is opened. There is no relevant error in Qtile.log, but journalctl shows the following:
```
feb 04 08:40:23 laptop systemd-coredump[31713]: [🡕] Process 31418 (qtile) of user 1000 dumped core.

                                                Module /usr/bin/python3.10 with build-id 12c63a5e2c0b1214b6384a2631e9515614ef42a3
                                                Stack trace of thread 31418:
                                                #0  0x00007f9ab92b1ca4 n/a (n/a + 0x0)
                                                ELF object binary architecture: AMD x86-64
```
I'd like to be able to debug these kind of problems better, but [the docs](https://docs.qtile.org/en/stable/manual/troubleshooting.html) don't go into low level debugging with Wayland, so I really don't know what my options are.

**Comment by justinesmithies** [comment]
Strange as I'm running the latest git master of Qtile under Wayland and it's running fine ?? I've loads of windows opened too.

**Comment by elParaguayo** [comment]
Our tests would fail too if that were the case.

@arjan-s this does sound like something specific to your setup. Have you had wayland running before? what versions of wlroots and pywlroots are you running?

**Comment by arjan-s** [comment]
Yeah, I'm sorry! @justinesmithies is right, current git master works just fine.
I forgot to disable the merging in of https://github.com/qtile/qtile/pull/2852 in my build script, which worked fine until one of the last master commits.
Anyway, I guess now this ticket should be more about the docs describing how to get stacktraces than about my crash specifically...

**Comment by m-col** [comment]
Great idea. Debug logs can be helpful but are obviously limited. You can also set `WAYLAND_DEBUG=1` which will give you incredibly verbose output at the lowest wayland level. You can do that with individual clients within a running session, or also with Qtile itself (I don't suggest that though, unless you're developing using the `wephyr` script, then it can be helpful sometimes). Any strack traces that qtile spits out while running isn't logged but is instead output to the TTY, which is obviously not very helpful. Maybe there is a way we can direct all stack traces to the logs, otherwise maybe redirected stderr might be fine.

Either way, I agree a paragraph describing this will be helpful, so unless anyone else wants to look into this, I can submit a PR probably on Sunday.

**Comment by arjan-s** [comment]
Just tried running it from the console, fully expecting a nice Python traceback... But I just got the segmentation fault again without any details. I do some Python for work myself and I really don't understand what's happening, it doesn't even look like a Python error.
So in short I'm really looking forward to your paragraph! :)

**Comment by elParaguayo** [comment]
@arjan-s Is the original issue solved? It looked like you did have it running a couple of posts ago but your last post suggests there's still an issue.

**Comment by arjan-s** [comment]
@elParaguayo well, that depends :)
The current git works just fine. My original issue turned out to be that the screen locker (a hard requirement at work) branch merged into master caused Qtile to crash, and still does.
Ater that the discussion went into how to debug such crashes, and I don't believe @m-col has already had time to write that down.

**Comment by m-col** [comment]
> My original issue turned out to be that the screen locker (a hard requirement at work) branch merged into master caused Qtile to crash, and still does.

Do you mean the idle and idle-inhibit protocol support? I think screen lockers won't yet work until input-inhibit is supported too (there is an open PR for this). Did those merges cause additional crashes or are you just getting the original one?

**Comment by arjan-s** [comment]
No, I do mean the PR for the input inhibit protocol. It's what's needed to run screenlockers like swaylock. Merging this PR into master wasn't a problem before, but it started crashing at some point, I think when the idle protocol wa merged.

**Comment by m-col** [comment]
Ah OK. That input-inhibitor PR probably needs a rebase then, and just isn't compatible any more. So if master is functional then all good. I will get to writing a small bit about debugging soon :)

**Comment by m-col** [comment]
The last release of pywayland enables logging of exceptions raised within wayland signals, which are critical to having actually useful logging. The lack of such logging was the main reason things have been so difficult to debug. Hopefully that helps a lot! Regardless, I've added a paragraph on the debugging environtal variable I mentioned above: https://github.com/qtile/qtile/pull/3547

Can you think of anything else that might be useful? The issue with 'getting the tracebacks out' should be resolved by the pywayland update - those will be logged to Qtile's normal log.

**Comment by arjan-s** [comment]
@m-col Very intermittently I still experience crashes, always running git master with the Wayland backend. Today I had another one. I went to the log file to find out what happened, but there was no error or traceback whatsoever. Should I have set `WAYLAND_DEBUG=1`, or should the traceback always be logged? Btw, I have pywayland 0.4.12, which is the newest version that includes the logging improvements.

**Comment by m-col** [comment]
Did it segfault and send you back to the TTY? I think when that happens we don't get much in the way of logs unfortunately. `WAYLAND_DEBUG=1` is very verbose so you probably don't want to run a regular session with it enabled, and if you run Qtile with it then it will also apply to all wayland clients, and I think it would be pretty difficult to read the output. It's kinda tricky but the only way to get more information is to try and identify the pattern of events leading up to the crash. Was any window being opened? What programs were open at the time? That kind of thing. I'm not really sure of a better way :/
