### ISSUE TITLE
Laggy mouse window movement with mouse polling rate set to 1000 Hz

### ISSUE THREAD

**Issue by thingsiplay** [qtile/qtile#3680]
### The issue:

I can't say if this is a specific issue with Qtile, but I never had this issue when I was still using Ubuntu with Gnome. Nowadays I am on Manjaro and use Qtile (and KDE as secondary login) and have a new mouse. So that's the backstory.

I purchased a new gaming mouse that is capable of setting the USB polling rate to 1000 Hz, which is double of standard USB rate (actually a regular mouse has a setting of 125 Hz, some gaming mices have higher rates such as 250 or 500 Hz and some even 1k like mine). When I set a window in Qtile to windowed mode and want to move it with mouse, then it is extremely laggy and the window is moving slowing to its final position where I dragged it with the mouse, following the path. When I set the mouse polling rate to 500 Hz, then the it is faster and not laggy that much. But it still is laggy. BTW setting the window size is the same problem.

* Your Qtile version

```
$ qtile --version
0.21.1.dev46+g2a0b9179
```

* Relevant **logs**

Nothing relevant (I think).

* If relevant, the problematic part of your config.

```
mouse = [

    Drag([mod, numlock], "Button1",
        lazy.window.set_position_floating(),
        start=lazy.window.get_position(),
    ),

    Drag([mod, numlock], "Button3",
        lazy.window.set_size_floating(),
        start=lazy.window.get_size(),
    ),

]
```

* Some system information as additional info:

```
OS: Manjaro Linux [x86_64]
Kernel: 5.18.7-1-MANJARO
Uptime: 22 hours, 51 mins
Packages: 2063 (pacman)[stable], 3 (flatpak)
Shell: zsh 5.9
Resolution: 2560x1440 @ 144Hz
DE: KDE Plasma 5.24.5
WM: Qtile 0.21.1.dev46+g2a0b9179 (X11)
Theme: breeze (GruvboxColors) [Plasma], Klaus [GTK2/3/4]
Icons: breeze [Plasma], Gruvbox [GTK2/3/4]
Font: Noto Sans (12pt) [Plasma], Noto Sans (12pt) [GTK2/3/4]
Cursor: default (24px)
Terminal: kitty
CPU: Intel Xeon E3-1230 v3 (8) @ 3.7GHz
GPU: Nvidia GeForce GTX 1070
Memory: 3924MiB / 15949MiB (24%)
Disk (/): 164GiB / 219GiB (74%)
Locale: de_DE.UTF-8
```

Note: I have searched for the issue and found this issue: https://github.com/qtile/qtile/issues/1584 I decided to create a new issue because it is more fleshed out with correct keywords and description of mouse polling rate. 

I assume the functions to set and get window positions have to be reworked in some way.

### Required:

- [x] I have searched past issues to see if this bug has already been reported.

**Comment by thingsiplay** [comment]
Is it possible to add some kind of pause into the function that is responsible for reading mouse actions? Some global setting that tells Qtile to check every 125ms for mouse position or similar. Does anyone know how to fix this? At the moment I can barely move windows that are floating.

**Comment by elParaguayo** [comment]
Is the issue happening on KDE too?

**Comment by thingsiplay** [comment]
No. To make sure, I just switched the login to KDE Plasma (X11) and also run the program Piper to set mouse polling rate (to make sure it is in effect). When I move a window in KDE, this issue does not happen. I also tested this by holding super key to drag window from any position, like I do in Qtile.

**Comment by M1ndo** [comment]
I'm facing the same issue, apparently this issue only exist in qtile for some reason, i use different window managers and tested both KDE And Gnome but the issue only exists in qtile.
if u could share ur patch, it will be helpful i can't add that by hand.
https://user-images.githubusercontent.com/44820142/179374943-c55e6729-fda2-44c1-b5df-dc89b12976b9.mp4

**Comment by nonetrix** [comment]
I've had this exact same issue in BSPWM the fix in BSPWM was ```bspc config pointer_motion_interval 60``` however this made moving windows feel like a slideshow but was slightly better

Annoying because QTile is perfect besides this I blame XOrg for being garbage as always I long for the day Wayland just works on NVIDIA 😅

**Comment by elParaguayo** [comment]
Fair enough. 

I think mcol mentioned a potential fix in that other thread (implementing the Sync extension).

I'll take a look at adding it.

**Comment by M1ndo** [comment]
@elParaguayo if you could provide potential fix somewhere soon that'd be really helpful and please tag me.

**Comment by thingsiplay** [comment]
I have some important semi-temporary-fix findings, that is reproducible on my system. And it is probably related to applications with their window accelerated by graphics cards, such as Kitty and Firefox. Because when I move a KDE application like Konsole or Dolphin window, when it is not overlapping Kitty or Firefox, then there is no lag. But as soon as I move the Dolphin filemanager window over Firefox, it becomes laggy. And this works while both applications are in floating mode in example or even if one is floating (let's say Dolphin) and Firefox is occupying only half of the screen on layout "stack" for example.

Let me know if you need some more information from xprop or any other thing. This lag problem is really annoying, as I have to deal with floating windows from time to time (dialogs in example or specific application windows forced to be floating such as RetroArch).

**Comment by mcnuggetsx20** [comment]
@elParaguayo any updates on solving the issue?

**Comment by thingsiplay** [comment]
I just found out another thing that is related to this problem. When I kill Picom, then there is no such lag. Even with the previously talked applications Kitty and Firefox overlapping. As soon as I run Picom, the lag comes back. So:

* high DPI mouse
* \+ windows accelerated by graphics card overlapping another window
* \+ plus Picom running

causes this terrible lag with floating windows.

**Comment by thingsiplay** [comment]
Okay, I think I found it! Disabling in Picom configuration `vsync = false;` will remove the lag! So I am not entirely sure if this is a problem with Picom itself or if this is something implemented in Qtile. I don't know how this setting will affect my system, but I thought to letting you know. Not sure if I should close this issue now.

**Comment by mcnuggetsx20** [comment]
Disabling picom does help a little bit, but window movement is still bad. Also vsync option is ignored when using experimental backends for blurring (I'm using jonaburg picom) so it doesn't matter if you set it to `true` or `false`, it's still gonna assume `true`. We still need a fix to this issue desperately.

**Comment by thingsiplay** [comment]
I just found out that the window movement is only fixed for some applications, but not for all. In example the movement (and resizing) is fixed for Kitty, but not for RetroArch. On the other hand, at least for RetroArch window the resizing is fixed, only movement is not. And that is with Picom running and `vsync = false;`. And at least for my system vsync option is not ignored with exprimental backend (commandline option is in effect + option is set in config file).

So yes, this issue is not fixed entirely. But for me it is much more usable now. Before that it was so bad I considered trying out other window managers.

**Comment by M1ndo** [comment]
@thingsiplay @mcnuggetsx20 In **Picom** disabling *vsync* has nothing to do with the issue also this not a picom bug, it might remove the lag but you'll get another terrible issue which is stuttering. 
Picom is just a compositor and this issue does not exist with other window managers (even with picom). You can also make sure that this issue still exists when **Xorg TearFree Enabled** which is **vsync** in *picom*.
The main issue in qtile is mouse polling rate which is inconsistent from (125, 500, and 1000 and upwards).

**Comment by jwijenbergh** [comment]
#4091 attempts to fix this by limiting the number of resizes we do, could anyone of you give it a spin?

**Comment by elParaguayo** [comment]
Closed by #4091

**Comment by stevenre3d** [comment]
The drag speed is improved, but is still very slow. There's still an issue here.

**Comment by thingsiplay** [comment]
I don't experience any issues with dragging or resizing anymore. Mouse set to 1000 Hz and monitor at 144 Hz.

**Comment by nonetrix** [comment]
Might not have been released yet use try the -git version in the Aur

**Comment by stevenre3d** [comment]
I'm running on Manjaro. Previously I had installed qtile from their repos (looks to be 0.22.1), but after experiencing the slow floating behavior I found this thread and realized I would have to run latest to try out the change. So I removed the package through pamac and cloned/installed directly from github. 

It's a dramatic improvement over the older version which could take 10s to move a window half way across my screen, but it's still noticeably slow. I can grab a floating window and move it around in circles multiple times, then stop moving my cursor and watch the window continue circling around for another maybe 100-500ms (it seems inconsistent).

Resizing behaves similarly, ranging from instant to a bit laggy. Redraw of the content seems to be dependent on the app. Steam and Firefox don't redraw until I stop moving, but Sublime Text redraws smoothly as I move.

While dragging the window around, I can also open gnome-system-monitor and watch one of my cores spike to 100% for the duration of me dragging the window. If I'm in discord and someone is talking, their voice crackles as it sounds like samples get dropped.

One more thing I noticed, not sure if this is a bug, but it's not ideal: I noticed that if I'm holding a mouse button to drag a window and my cursor crosses over to a different monitor/screen, the mouse button quickly gets released and re-pressed, potentially causing me to grab a completely different window and make it float (still using the default bindings for floating).

**Comment by thingsiplay** [comment]
What is your monitor Hz set to? Do you have Nvidia? Maybe G-Sync? Or V-Sync enabled? Do you use Picom? And if so, if you kill the picom process, do you still experience this issue?

Before all the recent changes I had the same problem where it could take several seconds before any movement stopped. The bigger the window, the slower it was. But only if an application like Kitty or Firefox that is GPU accelerated would overlap in windowed mode, then it would slow down. With applications that are not GPU accelerated, there was no issue.

**Comment by mcnuggetsx20** [comment]
I can confirm the issue is still there. The window I have the biggest problem with is Steam. Dragging it with mouse polling rage set to 1000 Hz is awful. Also `qtile-git` available in the aur seems to be outdated. Aur ships the version from 01.05.2022

![image](https://user-images.githubusercontent.com/71185521/211140226-c5bad982-57a7-4b7c-bcf8-eeb3a69f31d1.png)

The `qtile` package from the official arch repos is fortunately up to date but as someone said the `git` version is way better.

**Comment by elParaguayo** [comment]
You can ignore the date/package number for git packages in the AUR. That's just the details at the time the PKGBUILD was uploaded. Installing it will always install the latest version.

**Comment by mcnuggetsx20** [comment]
Ok it works with qtile-git. There indeed is an issue of picom making the movement choppy but I suppose it's none of your fault

**Comment by thingsiplay** [comment]
I use picom too. I am not sure if this is the right place to talk about this, but you can try to set the following **picom.conf** settings:
```
refresh-rate = 144;
backend = "glx";
experimental-backends = true;
```
Otherwise this is issue is solved now I guess.

**Comment by stevenre3d** [comment]
- As far as I know, I'm not using picom. (I'm still learning about the linux graphics/window stack, so I didn't even realize you could use a different compositor until today. According to a pamac search, nothing related to picom is marked as Installed.)
- I do have both a 60z and 144hz monitor, and the lag is more noticeable when dragging on the 144hz monitor.
- It does seem like the lag is more noticeable for apps that are GPU-accelerated, but is still app dependent.
- Windows being dragged over one another is also very related.

Some data points (tl;dr OBS seems to have the best behavior, Steam has the worst.)
- OBS: 
  - Dragging around rapidly over just the background: no noticeable lag when dragging around quickly on either the 60hz or 144hz. No spike in CPU.
  - Dragging around rapidly over other windows: noticeable lag over Firefox or Alacritty. Slightly noticeable on 60hz, very noticeable on 144hz. CPU cores spike.*
- Discord: 
  - Dragging around rapidly over just the background: Slight noticeable lag when dragging around, more noticeable on 144hz. Some CPU spikes.*
  - Dragging around rapidly over other windows: very noticeable lag over Firefox or Alacritty. CPU cores spike.*
- Firefox:
  - Always very noticeable lag when dragging it around on either 60hz or 144hz. CPU cores spike a lot.*
- Steam:
  - Always very noticeable lag, even worse than Firefox. Even worse on 144hz. CPU cores spike.*
  - Dragging anything over steam is super slow.

\* intensity _might_ correlate to which monitor I'm dragging around on. Hard to say for sure.

**Comment by thingsiplay** [comment]
Your description matches my experience (but I have only 144Hz) before the Qtile patches. So is there a chance you did not install the newest patched version for some reason? I am also on Manjaro + Nvidia (and use Piper BTW) and have installed the official Qtile Git version, that always installs the newest version. But I have to update it myself, as it won't get updated automatically. The command I use is (note you don't type `$`, it's just indicator a command input by user):

    $ yay -S -a --rebuild qtile-git

And the current version on my system is

    $ qtile --version
    0.22.2.dev101+g6a37adca

Just to get this out of the discussion. I don't notice ANY slowdown or problem with this anymore. But on the flip side, I have only one monitor (1440p/144Hz).

**Comment by stevenre3d** [comment]
I ran `pacman remove qtile`, then cloned this github and ran `pip install .` in the root, then rebooted.

My current version is:

```
$ qtile --version
0.22.2.dev102+gf0d07ecf
```

I can confirm that when I'm only using the 144hz monitor, FF and Discord float fine. Steam is still laggy, but not nearly as bad as when multiple monitors are attached.

If I instead only have the 60hz, I was surprised to find that not only is Steam laggy, but FF is too. It's worth noting the 60hz is 4k, and the 144hz is 1440p.

**Comment by mcnuggetsx20** [comment]
I have a 75 Hz and a 100 Hz monitor and with picom some windows (like Steam) drag choppy, but it's fine for the most part. Now Discord is my biggest issue as it's just as bad as before the qtile update even with picom disabled.

**Comment by jwijenbergh** [comment]
Apologies, can someone test #4141 to see if this fixes the issue as well (or better)? Seems like some of you were still having issues.

Maybe @stevenre3d @mcnuggetsx20? Sorry for pinging but I need some feedback

**Comment by jwijenbergh** [comment]
> Very sorry for the delay. I ended up trying out picom and despite everyone saying it was causing them issues, I found it helped me so that's what I've been using.

No problem, thanks for replying. Interesting that it works much better with picom, probs because of vsync (?)

> Yes I am using nvidia. I took some time to see what's changed. I disabled picom, checked out that `nvidia-resize` branch, installed it and restarted qtile, and everything was smooth. Then I tried checking out the merge-base of that branch and master, and it was still smooth. Then I tried going back to `0.22.2.dev102+gf0d07ecf` above where I documented that I was still having trouble, and it was smooth there too! I have run pamac updates since then, and updated my nvidia driver, so I wonder if it was an nvidia driver issue to begin with.
> 

That is weird! I think it's definitely still nice to limit these motion events. Have you perhaps changed mouse>

> Thank you all for your help, as far as I can tell it seems like this is resolved.

Great! Still unsure whether to merge the nvidia-resize branch or leave the current fix in master
