### ISSUE TITLE
QTile crashes on Arch after latest software update (after updates to QTile deps)

### ISSUE THREAD

**Issue by fpeterek** [qtile/qtile#4495]
### Issue description

On Arch Linux, QTile lists `python-cairocffi` and `python-xcffib` as its dependencies. Running a software update
bumped the version of those libraries.

`pacman` log:

```
21058   │ [2023-10-04T22:37:29+0200] [ALPM] upgraded python-cairocffi (1.5.1-1 -> 1.6.0-1)
21061   │ [2023-10-04T22:37:29+0200] [ALPM] upgraded python-xcffib (1.3.0-1 -> 1.4.0-1)
```

`pacman` package:

https://archlinux.org/packages/extra/x86_64/qtile/

Unfortunately, upon updating, QTile would crash on launch. Attempting to start QTile from the command line yielded
an `ImportError` importing modules from both both `cairocffi` and `xcffib`. There appear to be no relevant logs
in `qtile.log`.

After downgrading those two problematic dependencies with `pacman`, QTile started working again.

`sudo pacman -U /var/cache/pacman/pkg/python-xcffib-1.3.0-1-any.pkg.tar.zst`

If needed, I can later update the packages again and provide the exceptions. For now, I wanted to document
the issue and the necessary fix, in case somebody else stumbles upon the same problem.

Thank you.

### Version

0.22.1

### Backend

X11 (default)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by UshaKiranReddi** [comment]
Check this out -> https://bugs.archlinux.org/task/79856

**Comment by UshaKiranReddi** [comment]
Thank You!

**Comment by Koljasha** [comment]
I agree with this problem. It only helps:

- `sudo pacman -U /var/cache/pacman/pkg/python-xcffib-1.3.0-1-any.pkg.tar.zst`
- `sudo pacman -U /var/cache/pacman/pkg/python-cairocffi-1.5.1-1-any.pkg.tar.zst`

**Comment by BogdanBozic** [comment]
Man, I wish I saw this last night when I reinstalled the system. Thank you nonetheless, I can go back to using Qtile now!

**Comment by cnekmp** [comment]
Thanks. Awaiting for the fix...

**Comment by BouleJaune** [comment]
Hello,

I had the same problem yesterday, I filled a bug report on Arch and not an issue here since it's more about packaging rather than a Qtile bug. 
It is known I believe that newer versions of those dependencies only works with qtile 0.23 when Arch is on 0.22. I saw some issues there talking about it.

https://bugs.archlinux.org/task/79856

For those that do not have them cached anymore you can use 
``pacman -U https://archive.archlinux.org/packages/path/packagename.pkg.tar.zst``

Or the ``downgrade`` package (what I used)
https://github.com/archlinux-downgrade/downgrade

**Comment by fpeterek** [comment]
@BouleJaune my apologies, I had not seen that issue earlier. I know it's a packaging issue, I was just

a) hoping someone more involved in the QTile community and more knowledgeable about Arch packaging would be able to fix this

b) hoping by documenting the issue, other people would be able to fix it faster than I was, since I had to investigate it all myself

Since other people are struggling with the same problem, and the ticket has helped others fix their setups, I suggest we perhaps keep the issue until the Arch package has been fixed, so other people know how to deal with the problem, after which we can close the issue?

Thanks a lot

**Comment by pawamoy** [comment]
Thanks everyone, solved it with these commands:

```bash
yay -S downgrade
sudo downgrade python-xcffib==1.3.0
sudo downgrade python-cairocffi==1.5.1
```

**Comment by pawamoy** [comment]
@fpeterek the first thing I did was searching on Qtile's issue tracker, I'm very happy you opened the issue :+1:

**Comment by Koljasha** [comment]
now: qtile 0.23.0-1 in [extra-testing](https://archlinux.org/packages/extra-testing/x86_64/qtile/)
probably will be updated in the main branch soon....

**Comment by fpeterek** [comment]
Qtile 0.23.0 has just been released on Arch and the issue is now resolved. The packages from the pacman repositories are now compatible again and Qtile works without any tweaking.

@elParaguayo thanks for the pin, I presume you can now unpin this as it shouldn't cause problems anymore.

**Comment by pawamoy** [comment]
I'd suggest leaving it pinned for at least a few more days, just in case :slightly_smiling_face:

**Comment by elParaguayo** [comment]
The `PulseVolume` widget was rewritten.

From the `CHANGELOG`:
```- New optional dependency `pulsectl-asyncio` required for `PulseVolume` widget```

It's not in Arch repos yet but the qtile packager is looking at adding it.

If you can't wait, I can share a PKGBUILD file to install it.

**Comment by amrtn30** [comment]
Hi,

I just made a clean install of arch. I had some issues few hours ago, I understand now.

But I still have problems. Qtile launch but there is no characters, just squares. I guess the font is not loaded correctly. I just installed qtile and a terminal. Is there anything else to add ?

And the key shortcuts do not seem to work (for terminal and the prompt) for me.

**Comment by jamestrew** [comment]
> but I have new error: ` File "/usr/lib/python3.11/site-packages/libqtile/widget/pulse_volume.py", line 21, in <module> import pulsectl_asyncio ModuleNotFoundError: No module named 'pulsectl_asyncio'`

I resolved this by installing `pulsectl-asyncio` separately but that exposed another issue:
```
File "/usr/lib/python3.11/site-packages/pulsectl_asyncio/pulsectl_async.py", line 303, in _pulse_method_call
    func_args = list(inspect.getargspec(func or (lambda: None)))
                     ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'
```
Looks to be a python version issue though. 3.11's `inspect` module doesn't have a `getargspec` function.
I just removed the `PulseVolume` widget for now.

**Comment by elParaguayo** [comment]
You need `pulsectl-asyncio >= 1.0.0`. The AUR packages are out of date. This will be packaged in main repo soon.

**Comment by elParaguayo** [comment]
> The problem seems to be with the LTS kernel. With linux kernel it is ok.

Did you install any faults? I can't see why the kernel would impact that.

**Comment by Koljasha** [comment]
@elParaguayo 
I tried to install qtile and pulsectl-asyncio using pip, everything worked correctly on my configuration. I'm really looking forward to pulsectl-asyncio in the main archlinux repository.
If possible, please let me know when this happens so as not to monitor the repositories.

**Comment by amrtn30** [comment]
> > The problem seems to be with the LTS kernel. With linux kernel it is ok.
> 
> Did you install any fonts? I can't see why the kernel would impact that.

No, I just switch kernel.

**Comment by Koljasha** [comment]
Now there is no correct python-pulsectl-asyncio in the repository, here is the PKGBUILD:

```
pkgname=python-pulsectl-asyncio
_name=${pkgname#python-}
pkgver=1.1.1
pkgrel=1
pkgdesc="Asyncio frontend for pulsectl, a Python bindings library for PulseAudio (libpulse)"
arch=('any')
license=('MIT')
depends=('python' 'python-pulsectl')
makedepends=('python-build' 'python-installer' 'python-setuptools' 'python-wheel')
source=("https://files.pythonhosted.org/packages/source/${_name::1}/$_name/$_name-$pkgver.tar.gz")
sha256sums=('b5976b0ddd235d9ccc3455a03be664f7cb2201c942993b03ceb6b39d9cea8ad0')

build() {
  cd "$_name-$pkgver"
  python -m build --wheel --no-isolation
}

package() {
  cd "$_name-$pkgver"
  python -m installer --destdir="$pkgdir" dist/*.whl
}
```

**Comment by Koljasha** [comment]
> You need `pulsectl-asyncio >= 1.0.0`. The AUR packages are out of date. This will be packaged in main repo soon.

@elParaguayo Hello, is there any information about packages?

**Comment by elParaguayo** [comment]
No idea. The arch packaging is nothing to do with me. I know they were going to look at it but I haven't heard

**Comment by Koljasha** [comment]
> No idea. The arch packaging is nothing to do with me. I know they were going to look at it but I haven't heard

Thank you, I will hope for packages in the main repository.
Above I wrote a PKGBUILD, maybe it will be useful to someone
