### ISSUE TITLE
Xwayland apps on wayland

### ISSUE THREAD

**Issue by Gurjaka** [qtile/qtile#5101]
### Issue description

![image](https://github.com/user-attachments/assets/390dc158-6e4d-4e98-af0b-2b74da5bee0e)
First I discovered this issue when turning on Steam, later discovered that none Xwayland app works, even after running in terminal I get no output about error. This is all I got: ```❯ steam                                                                               
steam.sh[9848]: Running Steam on nixos 25.05 64-bit
steam.sh[9848]: STEAM_RUNTIME is enabled automatically
setup.sh[9896]: Steam runtime environment up-to-date!
steam.sh[9848]: Steam client's requirements are satisfied
CProcessEnvironmentManager is ready, 6 preallocated environment variables.
[2024-11-26 21:52:42] Startup - updater built Nov 12 2024 17:09:08
[2024-11-26 21:52:42] Startup - Steam Client launched with: '/home/gurami/.local/share/Steam/ubuntu12_32/steam' '-srt-logger-opened'
11/26 21:52:42 minidumps folder is set to /tmp/dumps
11/26 21:52:42 Init: Installing breakpad exception handler for appid(steam)/version(1731433018)/tid(9958)
src/steamexe/updateui_xwin.cpp (341) : Could not open connection to X
src/steamexe/updateui_xwin.cpp (341) : Could not open connection to X
11/26 21:52:42 Init: Installing breakpad exception handler for appid(steam)/version(1731433018)/tid(9958)
Error: Check your DISPLAY environment variable and make sure that you have enabled X.
If you are running remotely, make sure that you have a remote connection which will allow an X connection.

For more information visit https://support.steampowered.com/kb_article.php?ref=4050-WOJB-0608
Using host zenity for message
assert_20241126215242_4.dmp[9963]: Uploading dump (out-of-process)
/tmp/dumps/assert_20241126215242_4.dmp
src/steamexe/main.cpp (1328) : failed to initialize update status ui, or create initial window
src/steamexe/main.cpp (1328) : failed to initialize update status ui, or create initial window
11/26 21:52:42 Init: Installing breakpad exception handler for appid(steam)/version(1731433018)/tid(9958)
assert_20241126215242_7.dmp[9967]: Uploading dump (out-of-process)
/tmp/dumps/assert_20241126215242_7.dmp
~ 
❯ assert_20241126215242_7.dmp[9967]: Finished uploading minidump (out-of-process): success = yes
assert_20241126215242_7.dmp[9967]: response: CrashID=bp-d24466c0-21b4-45ce-a0d9-3cf602241126
assert_20241126215242_7.dmp[9967]: file ''/tmp/dumps/assert_20241126215242_7.dmp'', upload yes: ''CrashID=bp-d24466c0-21b4-45ce-a0d9-3cf602241126''
assert_20241126215242_4.dmp[9963]: Finished uploading minidump (out-of-process): success = yes
assert_20241126215242_4.dmp[9963]: response: CrashID=bp-38149775-6e7b-4400-a972-a50db2241126
assert_20241126215242_4.dmp[9963]: file ''/tmp/dumps/assert_20241126215242_4.dmp'', upload yes: ''CrashID=bp-38149775-6e7b-4400-a972-a50db2241126''```

### Version

0.29.0+37b0780.flake

### Backend

Wayland (experimental)

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by elParaguayo** [comment]
@tych0 I think this is caused by removing the double fork.

I get the following error `waitpid for Xwayland fork failed: No child processes` which, from a 2 second search, seems to be caused by the `SIGCHLD` handler (see https://github.com/djpohly/dwl/issues/177#issuecomment-1081241033 and fix in https://github.com/djpohly/dwl/pull/212).

**Comment by tych0** [comment]
Ah man, that is... unfortunate.

I don't think it's double fork, but our SIGCHLD handler, based on: https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/871646d22522141c45db2c0bfa1528d595bb69df the wlroots library wants to fork (which seems slightly impolite) an X server. When its waitpid() races with our SIGCHLD handler, it fails.

I think if wlroots really wants to do this, they should mask off the SIGCHLD handler while they're doing their own thing. Probably we should send them a patch, but in the meantime, we can manage it ourselves. Does: https://github.com/tych0/qtile/commit/dbe76e9ff5a193e8d1c7f805a861ac602925f547 work?

If not, we'll have to do something like what the patch you linked did (or maybe pywlroots should, like I mention https://github.com/flacjacket/pywlroots/pull/207 ?). But really wlroots proper should do that. I don't have enough wayland-fu to be building my own wayland stuff to test patches, though.

**Comment by elParaguayo** [comment]
Your patch works for me.

Would be good to get @jwijenbergh thoughts here too as he's more familiar with the wlroots stuff.

**Comment by tych0** [comment]
Ok, thanks for confirming. Happy to wait for @jwijenbergh's review, although I am reasonably confident that's the right fix given the implementations you linked to.

I will have a think about how wlroots can really handle this. it feels like double `posix_spawn()` is pretty heavyweight for them, but also forking in library code means many downstream users have to do tap dancing like this to get things to work correctly, which is unfortunate.

**Comment by tych0** [comment]
It turns out they already do some pipe-notify thing for xwayland, and so this waitpid() is just about zombie prevention, so I think we can safely ignore it. I sent them a patch: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4926

If they merge it, then once we move to that wlroots version, we can revert my fix.

**Comment by cr1ogen** [comment]
> I've merged your fix for now as it solves a real issue for some users. We can revert and implement a different fix if necessary later.

Hi, I started having this problem when I updated to the latest dev. Do you know how to go back to a previous version? Thanks

**Comment by tych0** [comment]
Can you say exactly which commit you're on (`qtile --version`)? The latest version should have it fixed.

**Comment by cr1ogen** [comment]
> Can you say exactly which commit you're on (`qtile --version`)? The latest version should have it fixed.

Of course
`qtile --version
0.29.1.dev41+g4897d0d1`

**Comment by cr1ogen** [comment]
> > Can you say exactly which commit you're on (`qtile --version`)? The latest version should have it fixed.
> 
> Of course `qtile --version 0.29.1.dev41+g4897d0d1`

I upgraded my Debian system and I no longer have the problem. Sorry if I wasted your time.

**Comment by cr1ogen** [comment]
I don't know if it's relevant, but if I run an Xwayland Window and then run steam inside it, it works.

**Comment by Gurjaka** [comment]
> I don't know if it's relevant, but if I run an Xwayland Window and then run steam inside it, it works.

I dont really understand how that works but steam isnt native to wayland so it runs xwayland

**Comment by tych0** [comment]
> I don't know if it's relevant, but if I run an Xwayland Window and then run steam inside it, it works.

I'm confused. I thought the issue was fixed?

**Comment by cr1ogen** [comment]
> > I don't know if it's relevant, but if I run an Xwayland Window and then run steam inside it, it works.
> 
> I'm confused. I thought the issue was fixed?

Maybe it's a problem with my system so I don't want to bother you, I use debian sid. Have you been able to reproduce it again?

**Comment by tych0** [comment]
> Maybe it's a problem with my system so I don't want to bother you, I use debian sid. Have you been able to reproduce it again?

I believe the patch fixes the issue, so it's likely yours is something different. I don't use wayland myself, so I was never able to reproduce it.

**Comment by cr1ogen** [comment]
> > Maybe it's a problem with my system so I don't want to bother you, I use debian sid. Have you been able to reproduce it again?
> 
> I believe the patch fixes the issue, so it's likely yours is something different. I don't use wayland myself, so I was never able to reproduce it.

I have 2 erros in my log file

`2024-12-02 17:21:00,670 WARNING libqtile base.py:__getattr__():L273 Deprecation Warning: commands exposed via IPC no longer use the 'cmd_' prefix. Please replace 'cmd_spawn' with 'spawn' in your code.`

`2024-12-02 18:09:51,824 ERROR wlroots log.py:log_func_callback():L15 [xwayland/server.c:261] waitpid for Xwayland fork failed: No hay ningún proceso hijo`

**Comment by cr1ogen** [comment]
In hyprland work 

this is qtile
```Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/libqtile/ipc.py", line 180, in async_send
    reader, writer = await asyncio.wait_for(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/streams.py", line 97, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/unix_events.py", line 261, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 659, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/qtile", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/scripts/main.py", line 79, in main
    func(options)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/scripts/cmd_obj.py", line 178, in cmd_obj
    ret = run_function(obj, args.function, args.args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/scripts/cmd_obj.py", line 132, in run_function
    ret = client.call(funcname, *args, lifted=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/command/client.py", line 126, in call
    if name not in self.commands:
                   ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/command/client.py", line 146, in commands
    return self._command.execute(command_call, (), {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/command/interface.py", line 248, in execute
    status, result = self._client.send(
                     ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/ipc.py", line 171, in send
    return asyncio.run(self.async_send(msg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/ipc.py", line 184, in async_send
    raise IPCError(f"Could not open {self.socket_path}")
libqtile.ipc.IPCError: Could not open /home/cr1ogen/.cache/qtile/qtilesocket.wayland-1
```

**Comment by tych0** [comment]
> 2024-12-02 18:09:51,824 ERROR wlroots log.py:log_func_callback():L15 [xwayland/server.c:261] waitpid for Xwayland fork failed: No hay ningún proceso hijo

This one should be fixed in the current git master. You're saying you get it still? Can you confirm which qtile version you're on?

**Comment by tych0** [comment]
Assuming it's the one you posted here: https://github.com/qtile/qtile/issues/5101#issuecomment-2511930357 I wouldn't expect you to see it.

Can you add some logging around the areas in e73ea6ee40b91807500811c398f56a37e3ba165a to see what exactly happens when if so? I wonder if we are racing and installing the signal handler still before xwayland starts up somehow.

**Comment by cr1ogen** [comment]
> > 2024-12-02 18:09:51,824 ERROR wlroots log.py:log_func_callback():L15 [xwayland/server.c:261] waitpid for Xwayland fork failed: No hay ningún proceso hijo
> 
> This one should be fixed in the current git master. You're saying you get it still? Can you confirm which qtile version you're on?

I'm still have it 
`qtile --version       
0.29.1.dev41+g4897d0d1`

**Comment by cr1ogen** [comment]
> Assuming it's the one you posted here: [#5101 (comment)](https://github.com/qtile/qtile/issues/5101#issuecomment-2511930357) I wouldn't expect you to see it.
> 
> Can you add some logging around the areas in [e73ea6e](https://github.com/qtile/qtile/commit/e73ea6ee40b91807500811c398f56a37e3ba165a) to see what exactly happens when if so? I wonder if we are racing and installing the signal handler still before xwayland starts up somehow.

Is it for me? Or maybe you forgot to tag someone? I don't understand how to do it.

**Comment by tych0** [comment]
> Is it for me? Or maybe you forgot to tag someone? I don't understand how to do it.

Yes, I'd like to fix this if you are still experiencing the problem, but I don't run wayland and therefore can't reproduce, so I need some information to debug it. In particular, I'd like to know the order of:

1. when we start xwayland
2. when we install the SIGHILD handler
3. when we reap the xwayland pid (probably just log all pids from the SIGCHILD handler)

**Comment by cr1ogen** [comment]
> > Is it for me? Or maybe you forgot to tag someone? I don't understand how to do it.
> 
> Yes, I'd like to fix this if you are still experiencing the problem, but I don't run wayland and therefore can't reproduce, so I need some information to debug it. In particular, I'd like to know the order of:
> 
> 1. when we start xwayland
> 2. when we install the SIGHILD handler
> 3. when we reap the xwayland pid (probably just log all pids from the SIGCHILD handler)

Sorry, I have no idea how to do what you're asking, I'm just an end user. If you could be more specific I would appreciate it.

**Comment by tych0** [comment]
Yes, please add some `logging.error("hello world from XYZ")` statements in the code, at the places I listed above, and install it as you normally do a development version of qtile. Then they should show up in your qtile.log, and you can figure out the ordering of what happens above.

**Comment by cr1ogen** [comment]
> Yes, please add some `logging.error("hello world from XYZ")` statements in the code, at the places I listed above, and install it as you normally do a development version of qtile. Then they should show up in your qtile.log, and you can figure out the ordering of what happens above.

Sorry, I tried to do it but it doesn't work. You will need a collaborator who is using qtile wayland, I apologize.

**Comment by tych0** [comment]
Can you say more about what didn't work? Your log messages didn't show up?

**Comment by cr1ogen** [comment]
I don't know how to put what you're asking me `logging.error("hello world from XYZ")` 
in this part
> Can you add some logging around the areas in 
[e73ea6e](https://github.com/qtile/qtile/commit/e73ea6ee40b91807500811c398f56a37e3ba165a) to see what exactly happens when if so? I wonder if we are racing and installing the signal handler still before xwayland starts up somehow.

**Comment by tych0** [comment]
You can just edit the file and install it as you would a normal development version of qtile.

**Comment by tych0** [comment]
Ideally all three, I'd like to know when the events from each happen.

**Comment by cr1ogen** [comment]
I put what you told me but in qtile.log no error appears, only this `2024-12-08 20:52:42,935 ERROR wlroots log.py:log_func_callback():L15 [xwayland/server.c:261] waitpid for Xwayland fork failed: There is no child process` I must be doing something wrong

**Comment by tych0** [comment]
I suspect the qtile you are installing and the qtile you are actually running are different versions. I would double check that you're running the custom installed qtile instead of one from distro packaging or whatever else.

**Comment by cr1ogen** [comment]
I discovered something that happens to me in Qtile. I use Waypaper as wallpaper manager, for some reason when I start Qtile, the wallpaper doesn't appear.
Now, if I want to start Steam or any X11 application before launching waypaper and choose a wallpaper, I get the error
`ERROR wlroots log.py:log_func_callback():L15 [xwayland/server.c:261] waitpid for Xwayland fork failed: There is no child process`
but if I choose the wallpaper before launching any X11 application it works without problems

**Comment by cr1ogen** [comment]
I was looking and it's like when there is no wallpaper, Xwayland can't start, since I put a wallpaper with the Qtile manager and an Xwayland process was formed and when I closed that process it gave the child process error, and it only works again if I start Xwayland manually.

**Comment by tych0** [comment]
I am not really a wayland person, but it could be that someone else is starting xwayland in that case, so wlroots doesn't have to? Not sure. Either way, I really do think the patch I have landed fixes the bug, so I would try to confirm which version of qtile you are actually running, since I believe the bug is fixed.

**Comment by cr1ogen** [comment]
![241209_17-04-28](https://github.com/user-attachments/assets/945a26f7-7c8b-438f-9ce7-6fb6c1b9e306)

**Comment by cr1ogen** [comment]
![241209_17-07-08](https://github.com/user-attachments/assets/0f115504-0a31-4c86-833d-93400f75a6e0)

**Comment by tych0** [comment]
Can you confirm that the version that you get from your shell is the same as the version that your xsession starts?

**Comment by cr1ogen** [comment]
> Can you confirm that the version that you get from your shell is the same as the version that your xsession starts?

If you mean that Xsession and Wayland-session are the same version, I confirm

**Comment by tych0** [comment]
Ok. Can you add the log messages so we can figure out what order things are happening in that causes the issue?

**Comment by cr1ogen** [comment]
```2024-12-09 17:17:53,561 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/home/cr1ogen/Git/pywlroots-0.17.0/.eggs/pywayland-0.4.18-py3.12-linux-x86_64.egg/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/core.py", line 728, in _on_cursor_button
    handled = self._process_cursor_button(button, pressed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/core.py", line 1189, in _process_cursor_button
    self._hovered_window.process_button_click(
  File "/usr/local/lib/python3.12/dist-packages/libqtile/bar.py", line 538, in process_button_click
    widget.button_press(
  File "/usr/local/lib/python3.12/dist-packages/libqtile/widget/tasklist.py", line 480, in button_press
    base._Widget.button_press(self, x, y, button)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/widget/base.py", line 295, in button_press
    cmd()
  File "/usr/local/lib/python3.12/dist-packages/libqtile/widget/tasklist.py", line 491, in select_window
    window.toggle_minimize()
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/window.py", line 706, in toggle_minimize
    self.minimized = not self.minimized
    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/window.py", line 508, in minimized
    self.floating = False
    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/window.py", line 434, in floating
    self.group.mark_floating(self, False)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/group.py", line 342, in mark_floating
    i.add_client(win)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/layout/plasma.py", line 952, in add_client
    self.root.restore(new)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/layout/plasma.py", line 634, in restore
    node.siblings[0].size = sizes[1]
    ~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-12-09 17:17:53,931 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/home/cr1ogen/Git/pywlroots-0.17.0/.eggs/pywayland-0.4.18-py3.12-linux-x86_64.egg/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/core.py", line 728, in _on_cursor_button
    handled = self._process_cursor_button(button, pressed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/core.py", line 1189, in _process_cursor_button
    self._hovered_window.process_button_click(
  File "/usr/local/lib/python3.12/dist-packages/libqtile/bar.py", line 538, in process_button_click
    widget.button_press(
  File "/usr/local/lib/python3.12/dist-packages/libqtile/widget/tasklist.py", line 480, in button_press
    base._Widget.button_press(self, x, y, button)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/widget/base.py", line 295, in button_press
    cmd()
  File "/usr/local/lib/python3.12/dist-packages/libqtile/widget/tasklist.py", line 491, in select_window
    window.toggle_minimize()
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/window.py", line 706, in toggle_minimize
    self.minimized = not self.minimized
    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/window.py", line 505, in minimized
    self._reconfigure_floating(new_float_state=FloatStates.MINIMIZED)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/window.py", line 571, in _reconfigure_floating
    self.group.mark_floating(self, True)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/group.py", line 327, in mark_floating
    self.tiled_windows.remove(win)
KeyError: XdgWindow(name='Mozilla Firefox', wid=8)
2024-12-09 17:24:25,624 WARNING libqtile base.py:__getattr__():L273 Deprecation Warning: commands exposed via IPC no longer use the 'cmd_' prefix. Please replace 'cmd_spawn' with 'spawn' in your code.
2024-12-09 17:26:15,827 ERROR wlroots log.py:log_func_callback():L15 [xwayland/server.c:261] waitpid for Xwayland fork failed: No hay ningún proceso hijo
```

The qtile.log complete  https://gist.github.com/cr1ogen/38f467283d8642e47fbb7c1c808c0cec

**Comment by cr1ogen** [comment]
```
2024-12-15 20:42:30,504 WARNING libqtile base.py:__getattr__():L273 Deprecation Warning: commands exposed via IPC no longer use the 'cmd_' prefix. Please replace 'cmd_spawn' with 'spawn' in your code.
2024-12-15 20:42:30,585 WARNING libqtile base.py:__getattr__():L273 Deprecation Warning: commands exposed via IPC no longer use the 'cmd_' prefix. Please replace 'cmd_spawn' with 'spawn' in your code.
2024-12-15 20:42:33,884 ERROR wlroots log.py:log_func_callback():L15 [xwayland/server.c:261] waitpid for Xwayland fork failed: No hay ningún proceso hijo
2024-12-15 20:43:05,232 ERROR wlroots log.py:log_func_callback():L15 [libinput] event7  - Razer Razer DeathAdder: client bug: event processing lagging behind by 32ms, your system is too slow

2024-12-15 20:43:38,772 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/home/cr1ogen/Git/pywlroots-0.17.0/.eggs/pywayland-0.4.18-py3.12-linux-x86_64.egg/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/core.py", line 728, in _on_cursor_button
    handled = self._process_cursor_button(button, pressed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/core.py", line 1189, in _process_cursor_button
    self._hovered_window.process_button_click(
  File "/usr/local/lib/python3.12/dist-packages/libqtile/bar.py", line 538, in process_button_click
    widget.button_press(
  File "/usr/local/lib/python3.12/dist-packages/libqtile/widget/tasklist.py", line 480, in button_press
    base._Widget.button_press(self, x, y, button)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/widget/base.py", line 295, in button_press
    cmd()
  File "/usr/local/lib/python3.12/dist-packages/libqtile/widget/tasklist.py", line 491, in select_window
    window.toggle_minimize()
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/window.py", line 706, in toggle_minimize
    self.minimized = not self.minimized
    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/window.py", line 508, in minimized
    self.floating = False
    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/window.py", line 434, in floating
    self.group.mark_floating(self, False)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/group.py", line 342, in mark_floating
    i.add_client(win)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/layout/plasma.py", line 952, in add_client
    self.root.restore(new)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/layout/plasma.py", line 634, in restore
    node.siblings[0].size = sizes[1]
    ~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-12-15 20:43:39,281 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
Traceback (most recent call last):
  File "/home/cr1ogen/Git/pywlroots-0.17.0/.eggs/pywayland-0.4.18-py3.12-linux-x86_64.egg/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/core.py", line 728, in _on_cursor_button
    handled = self._process_cursor_button(button, pressed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/core.py", line 1189, in _process_cursor_button
    self._hovered_window.process_button_click(
  File "/usr/local/lib/python3.12/dist-packages/libqtile/bar.py", line 538, in process_button_click
    widget.button_press(
  File "/usr/local/lib/python3.12/dist-packages/libqtile/widget/tasklist.py", line 480, in button_press
    base._Widget.button_press(self, x, y, button)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/widget/base.py", line 295, in button_press
    cmd()
  File "/usr/local/lib/python3.12/dist-packages/libqtile/widget/tasklist.py", line 491, in select_window
    window.toggle_minimize()
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/window.py", line 706, in toggle_minimize
    self.minimized = not self.minimized
    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/window.py", line 505, in minimized
    self._reconfigure_floating(new_float_state=FloatStates.MINIMIZED)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/backend/wayland/window.py", line 571, in _reconfigure_floating
    self.group.mark_floating(self, True)
  File "/usr/local/lib/python3.12/dist-packages/libqtile/group.py", line 327, in mark_floating
    self.tiled_windows.remove(win)
KeyError: XdgWindow(name='Xwayland on :0', wid=9)
2024-12-15 20:44:02,012 WARNING libqtile base.py:__getattr__():L273 Deprecation Warning: commands exposed via IPC no longer use the 'cmd_' prefix. Please replace 'cmd_spawn' with 'spawn' in your code.
```

**Comment by elParaguayo** [comment]
I'm actually still hitting this bug too but it's intermittent.

**Comment by Gurjaka** [comment]
> I'm actually still hitting this bug too but it's intermittent.

Hm, made the change to wayland?

**Comment by cr1ogen** [comment]
> I'm actually still hitting this bug too but it's intermittent.

If it is intermittent, in my case more than less xD

**Comment by Gurjaka** [comment]
Tbh I haven't faced that issue in a while, got to check latest commits

**Comment by elParaguayo** [comment]
It seems that some apps trigger a crash and others don't.

**Comment by jwijenbergh** [comment]
Yeah I can reproduce this, sometimes *NO* xwayland apps start. The only way to fix it is to restart qtile

**Comment by Gurjaka** [comment]
> Yeah I can reproduce this, sometimes _NO_ xwayland apps start. The only way to fix it is to restart qtile

I myself haven't faced this issue in a while, weird

**Comment by arjan-s** [comment]
I'm encountering this issue as well. It's a regression in 0.30.0 and is what is keeping https://github.com/NixOS/nixpkgs/pull/371737 from being merged.

What I see happening as a user is the following:
- Qtile starts an Xwayland process on login
- The Xwayland process quits after 10 seconds if it isn't being used
- Once some application needs Xorg, Qtile 0.29.0 starts a new Xwayland process, but Qtile 0.30.0 doesn't

When I start an Xorg application within 10 seconds after login, it uses the initial Xwayland process and it all works fine. Except when I quit it, then the Xwayland process quits after 10 seconds and I'm back to not having a working Xwayland.

**Comment by Gurjaka** [comment]
@tych0 I was scrolling through qtile wayland core code, and found this comment: https://github.com/qtile/qtile/blob/d57ddbe5b1d7fdfaf0d21ce4a00f658141276832/libqtile/backend/wayland/core.py#L375

then I checked your free desktop merge request to wlroots, which has been merged 1 month ago: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4926

so I think reverting the code might fix everything related to this topic, mind checking?

**Comment by jwijenbergh** [comment]
> so I think reverting the code might fix everything related to this topic, mind checking?

we would first have to move to a new wlroots

**Comment by Gurjaka** [comment]
> > so I think reverting the code might fix everything related to this topic, mind checking?
> 
> we would first have to move to a new wlroots

Only thing I can say is release 0.30.0 is buggy on wayland and we need new release that fixes this

**Comment by cr1ogen** [comment]
> > so I think reverting the code might fix everything related to this topic, mind checking?
> 
> we would first have to move to a new wlroots

wlroots .018 does not allow compiling pywlroots  https://github.com/flacjacket/pywlroots/issues/228

**Comment by cr1ogen** [comment]
and Flacjacket doesn't seem to be very active lately

**Comment by arjan-s** [comment]
A nice workaround for people who want to run 0.30.0 (or latest git master) but are plagued by this regression is to use [xwayland-satellite](https://github.com/Supreeeme/xwayland-satellite). Simply running it in a terminal will make Xwayland work again (better, even).

**Comment by Gurjaka** [comment]
> A nice workaround for people who want to run 0.30.0 (or latest git master) but are plagued by this regression is to use [xwayland-satellite](https://github.com/Supreeeme/xwayland-satellite). Simply running it in a terminal will make Xwayland work again (better, even).

Owww nicee

**Comment by cr1ogen** [comment]
> A nice workaround for people who want to run 0.30.0 (or latest git master) but are plagued by this regression is to use [xwayland-satellite](https://github.com/Supreeeme/xwayland-satellite). Simply running it in a terminal will make Xwayland work again (better, even).

When it doesn't work for me I simply launch Xwayland with

`Xwayland -geometry 3840x2160 -hidpi `

I also hope they fix it and I'm going to try that program

**Comment by arjan-s** [comment]
Yeah I tried manually running Xwayland (rootful) too, but that gives you only 1 space to work with, and no clipboard sync. xwayland-satellite makes it seamless like the integrated solution.

**Comment by Gurjaka** [comment]
I think it should be added to autostart like this:
```python
@hook.subscribe.startup_once
def autostart():
        subprocess.run("xwayland-sattelite &")
```

**Comment by cr1ogen** [comment]
Any news for this bug that I think is a priority for qtile?

**Comment by cr1ogen** [comment]
I was seeing that if I first launch a Wayland application, Xwayland will work afterward. But if I first launch an Xwayland window, it won't work anymore.

**Comment by koniiiik** [comment]
I think I might be experiencing the same issue, and I can consistently reproduce it. From what I've seen, as soon as the Xwayland server terminates (which it does after having no client connections for 10 seconds), it is never able to restart again. Here's a fragment of the qtile log at INFO level from one such instance:

```
2025-07-02 12:59:25,127 INFO libqtile core.py:__init__():L191 Starting core with WAYLAND_DISPLAY=wayland-0
2025-07-02 12:59:25,129 ERROR wlroots log.py:log_func_callback():L15 [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
2025-07-02 12:59:25,129 INFO libqtile core.py:__init__():L393 Set up XWayland with DISPLAY=:1
[… a number of lines about input devices and output modes …]
2025-07-02 12:59:25,558 INFO libqtile utils.py:guess_terminal():L392 Terminal found: alacritty
2025-07-02 12:59:25,712 WARNING libqtile prompt.py:_configure():L444 Prompt widget only supports audible bell under X11
2025-07-02 12:59:25,713 INFO libqtile bar.py:_configure():L354 The following widgets were renamed in qtile.widgets_map: textbox_1, textbox_2, textbox_3, textbox_4 To bind commands, rename the widget or use lazy.widget[new_name].
Environment variable $XDG_CURRENT_DESKTOP not set, ignoring.
2025-07-02 12:59:54,955 INFO wlroots log.py:log_func_callback():L17 [xwayland/server.c:108] Starting Xwayland on :1
2025-07-02 12:59:55,865 WARNING libqtile wlrq.py:finalize_listener():L234 Failed to remove listener for event: <pywayland.server.listener.Signal object at 0x7f51bc3776b0>
2025-07-02 12:59:55,866 WARNING libqtile wlrq.py:finalize_listener():L234 Failed to remove listener for event: <pywayland.server.listener.Signal object at 0x7f51bc377230>
2025-07-02 13:00:05,875 INFO wlroots log.py:log_func_callback():L17 [xwayland/server.c:215] Restarting Xwayland (lazy)
2025-07-02 13:02:07,447 INFO wlroots log.py:log_func_callback():L17 [xwayland/server.c:108] Starting Xwayland on :1
2025-07-02 13:02:07,509 ERROR wlroots log.py:log_func_callback():L15 [xwayland/server.c:261] waitpid for Xwayland fork failed: No child processes
```

If I don't keep at least one X client active throughout the entire session, Xwayland terminates, and never starts up again. If I make sure to start a persistent X client, everything is fine.

I've also tried to use xwayland-satellite as an alternative, but that doesn't seem to behave entirely correctly. It seems to run in a weird semi-rootful mode where a root window is created on demand when a client opens a window, and then other windows are also placed inside that root.
